
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cinevision?serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=root
spring.datasource.password=COLOQUE_SUA_SENHA_AQUI

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
